# 聚合操作

In [1]:
import numpy as np
L=np.random.random(100)

In [2]:
L

array([0.51007321, 0.30860005, 0.41421744, 0.89649251, 0.74722953,
       0.99672452, 0.2717249 , 0.8139846 , 0.42763065, 0.86464861,
       0.8426663 , 0.3137915 , 0.1804339 , 0.63904172, 0.90481852,
       0.8438436 , 0.15656758, 0.52362377, 0.85702984, 0.94916806,
       0.96549304, 0.93714919, 0.30954466, 0.95222815, 0.73243187,
       0.92294594, 0.77168505, 0.43546417, 0.60144997, 0.0920005 ,
       0.8693663 , 0.7609682 , 0.39586207, 0.73124993, 0.23138186,
       0.20228692, 0.86702687, 0.41738553, 0.64272151, 0.85648087,
       0.09939114, 0.27947392, 0.06936446, 0.34608025, 0.40556435,
       0.6803426 , 0.56006864, 0.89348269, 0.00882673, 0.87738082,
       0.08292816, 0.95329884, 0.02539504, 0.05369709, 0.50639274,
       0.96818147, 0.19788846, 0.99906841, 0.22973678, 0.86629069,
       0.85734698, 0.65432567, 0.09566155, 0.92824944, 0.52970401,
       0.03819383, 0.09641619, 0.40656117, 0.49997748, 0.51616317,
       0.61534677, 0.03746921, 0.21362345, 0.95273008, 0.42350

In [3]:
sum(L)

54.10913440841651

In [4]:
np.sum(L)

54.109134408416516

In [5]:
big_array=np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

143 ms ± 3.43 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.7 ms ± 88 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
np.min(big_array)

1.060647871642395e-06

In [8]:
big_array.min()

1.060647871642395e-06

In [9]:
big_array.max()

0.9999989889632438

In [10]:
x=np.arange(16).reshape(4,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.sum(x)

120

In [12]:
np.sum(x,axis=1)

array([ 6, 22, 38, 54])

In [13]:
np.sum(x,axis=0)

array([24, 28, 32, 36])

In [14]:
np.prod(x)

0

In [18]:
np.prod( x + 1)

2004189184

In [16]:
np.mean(x)

7.5

In [19]:
v=np.array([1,1,2,2,10])
np.mean(v)

3.2

In [20]:
np.median(v)

2.0

In [21]:
np.percentile(big_array,q=50)

0.5000546909306667

In [22]:
np.median(big_array)

0.5000546909306667

In [23]:
np.percentile(big_array,q=100)

0.9999989889632438

In [24]:
np.max(big_array)

0.9999989889632438

In [26]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big_array,q=percent))

1.060647871642395e-06
0.24974426677507547
0.5000546909306667
0.7488248797061152
0.9999989889632438


In [27]:
x=np.random.normal(0,1,size=1000000)

In [32]:
np.mean(x)

-0.0002466669344505147

In [29]:
np.std(x)

1.0007872526200714

## 索引

In [30]:
np.min(x)

-4.808401631594064

In [31]:
np.argmin(x)

647259

In [33]:
np.argmax(x)

203074

## 排序

In [34]:
x=np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
np.random.shuffle(x)
x

array([ 1, 14, 11,  7,  0,  4, 15, 10,  8,  6,  9,  5,  2,  3, 13, 12])

In [36]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
x.sort()

In [42]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
x=np.random.randint(10,size=(4,4))

In [44]:
x

array([[6, 4, 8, 9],
       [9, 2, 6, 4],
       [6, 3, 9, 1],
       [7, 9, 2, 5]])

In [45]:
np.size(x)

16

In [46]:
np.sort(x)

array([[4, 6, 8, 9],
       [2, 4, 6, 9],
       [1, 3, 6, 9],
       [2, 5, 7, 9]])

In [47]:
np.sort(x,axis=1)

array([[4, 6, 8, 9],
       [2, 4, 6, 9],
       [1, 3, 6, 9],
       [2, 5, 7, 9]])

In [48]:
np.sort(x,axis=0)

array([[6, 2, 2, 1],
       [6, 3, 6, 4],
       [7, 4, 8, 5],
       [9, 9, 9, 9]])

In [49]:
x

array([[6, 4, 8, 9],
       [9, 2, 6, 4],
       [6, 3, 9, 1],
       [7, 9, 2, 5]])

In [52]:
np.random.shuffle(x)

In [53]:
x

array([[6, 4, 8, 9],
       [7, 9, 2, 5],
       [9, 2, 6, 4],
       [6, 3, 9, 1]])

In [54]:
np.argsort(x)

array([[1, 0, 2, 3],
       [2, 3, 0, 1],
       [1, 3, 2, 0],
       [3, 1, 0, 2]], dtype=int64)

In [55]:
np.partition(x,3)

array([[4, 6, 8, 9],
       [2, 5, 7, 9],
       [2, 4, 6, 9],
       [1, 3, 6, 9]])

In [64]:
x=np.arange(16)
np.random.shuffle(x)
x

array([ 8,  3, 13,  1, 12, 11,  0,  5, 14,  7, 15,  4,  6, 10,  2,  9])

In [65]:
np.partition(x,3)

array([ 0,  1,  2,  3,  6,  4,  5,  7,  8, 14, 15, 11, 12, 10, 13,  9])

In [66]:
np.argpartition(x,3)

array([ 6,  3, 14,  1, 12, 11,  7,  9,  0,  8, 10,  5,  4, 13,  2, 15],
      dtype=int64)