# numpy.array中的运算

a=(0,1,2)
a*2=(0,2,4)

In [34]:
n=10
L=[i for i in range(n)]

In [35]:
2*L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
A=[]
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [37]:
n=1000000
L=[i for i in range(n)]
A=[]

In [38]:
%%time
A=[]
for e in L:
    A.append(2*e)
A

Wall time: 199 ms


In [39]:
%%time
A=[2*e for e in L]

Wall time: 142 ms


In [40]:
import numpy as np
L=np.arange(n)

In [41]:
%%time
A=np.array(2*e for e in L)

Wall time: 24 ms


In [42]:
%%time
A=2*L

Wall time: 2.97 ms


In [43]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [44]:
n=10
L=np.arange(n)
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Functions

In [46]:
x=np.arange(1,16).reshape((3,5))

In [49]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [50]:
x+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [51]:
x/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [52]:
x//2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [53]:
np.abs(x)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [54]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [55]:
np.exp(x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [56]:
np.power(3,x)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [57]:
np.log(x)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [58]:
np.log2(x)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

## 矩阵运算

In [59]:
A=np.arange(4).reshape(2,2)

In [60]:
A

array([[0, 1],
       [2, 3]])

In [62]:
B=np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [63]:
A-B

array([[-10,  -9],
       [ -8,  -7]])

In [64]:
A+B

array([[10, 11],
       [12, 13]])

In [65]:
A*B

array([[ 0, 10],
       [20, 30]])

In [66]:
A/B

array([[0. , 0.1],
       [0.2, 0.3]])

In [67]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [68]:
A

array([[0, 1],
       [2, 3]])

In [69]:
A.T

array([[0, 2],
       [1, 3]])

## 向量和矩阵的运算

In [70]:
v=np.array([1,2])

In [71]:
A

array([[0, 1],
       [2, 3]])

In [72]:
v+A

array([[1, 3],
       [3, 5]])

In [73]:
np.vstack([v]*A.shape[0])

array([[1, 2],
       [1, 2]])

In [74]:
np.vstack([v]*A.shape[0])+A

array([[1, 3],
       [3, 5]])

In [75]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [76]:
np.tile(v,(1,2))

array([[1, 2, 1, 2]])

## 矩阵的逆

In [77]:
A

array([[0, 1],
       [2, 3]])

In [78]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [79]:
invA=np.linalg.inv(A)

In [80]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [81]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [82]:
x=np.arange(16).reshape((2,8))

In [83]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [85]:
pinvx=np.linalg.pinv(x)

In [86]:
pinvx

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [87]:
pinvx.shape

(8, 2)

In [88]:
x.dot(pinvx)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])