# 实现混淆矩阵，精准率和召回率

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
digits = datasets.load_digits()
x=digits.data
y=digits.target.copy()

y[digits.target==9]=1
y[digits.target!=9]=0

In [3]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=666)

In [6]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [6]:
from sklearn.linear_model import LogisticRegression

log_reg=LogisticRegression()
log_reg.fit(x_train,y_train)
log_reg.score(x_test,y_test)

0.9755555555555555

In [10]:
y_log_predict=log_reg.predict(x_test)

In [8]:
def TN(y_true,y_predict):
    assert len(y_true)==len(y_predict)
    return np.sum((y_true==0)&(y_predict==0))

In [11]:
TN(y_test,y_log_predict)

403

In [12]:
def FP(y_true,y_predict):
    assert len(y_true)==len(y_predict)
    return np.sum((y_true==0)&(y_predict==1))

In [13]:
def FN(y_true,y_predict):
    assert len(y_true)==len(y_predict)
    return np.sum((y_true==1)&(y_predict==0))

In [14]:
def TP(y_true,y_predict):
    assert len(y_true)==len(y_predict)
    return np.sum((y_true==1)&(y_predict==1))

In [15]:
def confusion_matrix(y_true,y_predict):
    return np.array([
        [TN(y_true,y_predict),FP(y_true,y_predict)],
        [FN(y_true,y_predict),TP(y_true,y_predict)]
    ])

In [16]:
confusion_matrix(y_test,y_log_predict)

array([[403,   2],
       [  9,  36]])

In [19]:
def precision_score(y_true,y_predict):
    tp=TP(y_true,y_predict)
    fp=FP(y_true,y_predict)
    try:
        return tp/(tp+fp)
    except:
        return 0.0
precision_score(y_test,y_log_predict)

0.9473684210526315

In [20]:
def recall_score(y_true,y_predict):
    tp=TP(y_true,y_predict)
    fn=FN(y_true,y_predict)
    try:
        return tp/(tp+fn)
    except:
        return 0.0
recall_score(y_test,y_log_predict)

0.8

# scikit_learn中的混淆矩阵，精准率和召回率

In [21]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_log_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [23]:
from sklearn.metrics import precision_score

precision_score(y_test,y_log_predict)

0.9473684210526315

In [24]:
from sklearn.metrics import recall_score

recall_score(y_test,y_log_predict)

0.8