In [1]:
import numpy as np

In [14]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### 切片处理

In [3]:
x[3:9:2]

array([3, 5, 7])

### 元素乘积

In [13]:
x = np.arange(1,4)
np.prod(x)

6

### 求矩阵元素逆矩阵和伪逆矩阵

In [15]:
A = np.random.normal(0,1,(3,3))
B = np.linalg.inv(A)
print(B)

C = np.random.normal(0,1,(2,3))
D = np.linalg.pinv(C)
print(D)

[[ 0.39077234 -0.04060155 -0.38485873]
 [ 0.8200987  -0.43161798 -0.2145575 ]
 [ 0.07316971 -0.58251562 -0.28501512]]
[[ 0.22988881 -0.70621957]
 [ 0.50552847  0.23745916]
 [ 0.09760592  0.54372115]]


### 得到索引值

In [16]:
ind = [3,4,8]
x[ind]

array([3, 4, 8])

In [17]:
ind = np.array([[1,3],
               [2,5]])
x[ind]

array([[1, 3],
       [2, 5]])

In [46]:
X = x.reshape(4,-1)
print(X)
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 1,  6, 11])

In [42]:
X[0,col]

array([1, 2, 3])

In [43]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [44]:
col = [True,False,True,True]

In [47]:
X[1:3,col]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

### numpy.array的比较

In [50]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [54]:
2 * x ==24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [55]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
X > 6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [57]:
np.sum(x <= 6)

7

In [60]:
np.count_nonzero(x >= 8)

8

In [61]:
np.any(x == 0)

True

In [63]:
np.all(x == 0)

False

In [64]:
np.any(x >= 3)

True

In [67]:
np.all(x >= 0)

True

In [68]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
np.sum(X,axis = 0)

array([24, 28, 32, 36])

In [76]:
np.sum(X % 2==0)

8

In [78]:
np.sum(X%2==0,axis=0)

array([4, 0, 4, 0])

In [79]:
np.all(X > 0,axis = 1)

array([False,  True,  True,  True])

In [80]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### & 和 | 和 ~ 的用法

In [19]:
np.sum((x>3)&(x<10))

6

In [85]:
np.sum((x%2==0)|(x>10))

11

In [90]:
np.sum(~(x==0))

15

### 索引取值

In [103]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
x[x<5]

array([0, 1, 2, 3, 4])

In [93]:
x[x%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [101]:
X[X[:,-1]%3==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [104]:
X[:,-1]

array([ 3,  7, 11, 15])

### np.repeat

In [22]:
c = np.array([[1,2],
             [3,4]])
c

array([[1, 2],
       [3, 4]])

In [23]:
np.repeat(c,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [24]:
np.repeat(c,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [26]:
np.repeat(c,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [29]:
np.repeat(c,[2,4],axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])

In [30]:
np.repeat(c,[2,4],axis=1)

array([[1, 1, 2, 2, 2, 2],
       [3, 3, 4, 4, 4, 4]])