In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
raw_data_X = [[4.53105842, 6.07258236],
               [7.0002554 , 5.10556304],
               [3.14594633, 4.35090017],
               [4.12374144, 3.96951117],
               [7.34733056, 0.57979688],
               [4.3911134 , 2.81070192],
               [4.07728671, 2.16609599],
               [6.8806328 , 3.58590554],
               [0.75518827, 4.45492787],
               [1.97184703, 1.38370549]
             ]
raw_data_y = [0,0,0,0,0,1,1,1,1,1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([3.44762187, 1.45816142])
X_predict = x.reshape(1,-1)

In [4]:
%run D:/IntelliJ_python/初见机器学习/KNN/KNN.py

In [5]:
predict_y = KNN_classify(6,X_train,y_train,x)

In [6]:
predict_y

1

### 可以说kNN是一个不需要训练过程的算法
### k近邻算法是非常特殊的，可以被认为是没有模型的算法
### 为了和其他算法统一，可以认为训练数据集就是模型本身

# 使用scikit-learn中的kNN

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [9]:
kNN_classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

### 至此，模型已经训练完成

In [10]:
kNN_classifier.predict(X_predict)

array([0])

In [11]:
y_predict = kNN_classifier.predict(X_predict)

In [12]:
y_predict[0]

0

### pycharm整理kNN代码

In [19]:
%run D:/IntelliJ_python/初见机器学习/KNN/sklearn中的kNN.py

In [20]:
knn_clf = KNNClassifier(k=6)

In [21]:
knn_clf.fit(X_train,y_train)

kNN(k=6)

In [22]:
y_predict = knn_clf.predict(X_predict)

In [23]:
y_predict[0]

1

# 测试我们的算法

In [24]:
from sklearn import datasets

In [25]:
iris = datasets.load_iris()

In [26]:
X = iris.data
y = iris.target

In [27]:
X.shape

(150, 4)

In [28]:
y.shape

(150,)

### train_test_split

In [29]:
Concat = np.concatenate((X,y.reshape(150,1)),axis=1)

In [30]:
np.random.shuffle(Concat)
left,right = np.split(Concat,[4],axis=1)

In [31]:
shuffle_index = np.random.permutation(len(X))
shuffle_index

array([125, 113,  91, 133,  11,  78, 135, 110,  17,  72,  77, 102, 143,
        69,  33,  34,  94, 112,   8,  81, 130,  88,  80,  16,  54,  30,
       144, 116,  41, 146, 134, 145, 126, 131,  67,  79,  15,  48,   2,
        53,  28,  56,  50,  42, 136,  35, 138,  24, 100,   9,  74, 121,
        29,  65,  99,  37,  75,  68,  93,  90,   4, 122, 118,  58,  25,
        61,  51,  55,   3,  44,  95, 140,  96,  70,  71,  21,  27,  18,
       141, 119,   5,  49,  98,  36, 128, 109, 115,  83, 123,  59,  40,
       149,  85,  45,  60,  82, 106, 147,  64,  47, 142,  86, 104, 129,
       107, 105, 114,   7,  57,  23,  20, 117,  39,  13, 148,  52, 120,
        62,  10,  38, 139,   0,  14, 132,  46,   6, 108,  26,  89,   1,
        73, 127, 111,  32,  22,  63,  87, 137,  92,  76,  31, 103,  97,
        43,  12,  19,  66, 124, 101,  84])

In [32]:
test_ratio = 0.2
test_size = int(len(X)*test_ratio)
test_size

30

In [33]:
test_indexes = shuffle_index[:test_size]
train_indexes = shuffle_index[test_size:]

In [34]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [35]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [36]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [37]:
import os
os.chdir('D:/IntelliJ_python/初见机器学习')
os.getcwd()

'D:\\IntelliJ_python\\初见机器学习'

In [38]:
from KNN.model_selection import train_test_split

In [39]:
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [40]:
print(X_train.shape)

(120, 4)


In [41]:
from KNN.sklearn中的kNN import KNNClassifier

In [42]:
my_knn_clf = KNNClassifier(k=3)

In [43]:
my_knn_clf.fit(X_train,y_train)

kNN(k=3)

In [44]:
y_predict = my_knn_clf.predict(X_test)
y_predict

array([2, 0, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 0, 1, 2, 0, 0, 0, 1, 2,
       0, 0, 1, 1, 2, 1, 2, 2])

In [45]:
y_test

array([2, 0, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 0, 1, 2, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 2, 1, 1, 2])

In [46]:
sum(y_predict==y_test)

28

In [47]:
sum(y_predict == y_test)/len(y_test)

0.9333333333333333

### sklearn中的train_test_split

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=666)
#这里的random_state就是随机数种子

In [50]:
from sklearn.neighbors import KNeighborsClassifier

In [51]:
Knn_classifier = KNeighborsClassifier(n_neighbors = 3)
Knn_classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [52]:
y_predict = Knn_classifier.predict(X_test)

In [53]:
y_predict

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])