In [1]:
import numpy as np

In [2]:
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [4]:
X = iris.data
y = iris.target

In [5]:
X[:10,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=666)

### scikit-learn中的StandardScaler

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
standardScaler = StandardScaler()

In [9]:
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
standardScaler.mean_# 由于mean变量是由用户传进去的变量计算出来的，用户可以随时从外面进行查询，对于这种变量使用变量名后加_

array([5.83416667, 3.0825    , 3.70916667, 1.16916667])

In [11]:
standardScaler.scale_ #输出方差,描述数据分布范围

array([0.81019502, 0.44076874, 1.76295187, 0.75429833])

In [12]:
X_train = standardScaler.transform(X_train)

In [13]:
X_train

array([[-0.90616043,  0.94720873, -1.30982967, -1.28485856],
       [-1.15301457, -0.18717298, -1.30982967, -1.28485856],
       [-0.16559799, -0.64092567,  0.22169257,  0.17345038],
       [ 0.45153738,  0.72033239,  0.95909217,  1.49918578],
       [-0.90616043, -1.3215547 , -0.40226093, -0.0916967 ],
       [ 1.43895396,  0.2665797 ,  0.56203085,  0.30602392],
       [ 0.3281103 , -1.09467835,  1.07253826,  0.30602392],
       [ 2.1795164 , -0.18717298,  1.63976872,  1.2340387 ],
       [-0.78273335,  2.30846679, -1.25310662, -1.4174321 ],
       [ 0.45153738, -2.00218372,  0.44858475,  0.43859746],
       [ 1.80923518, -0.41404933,  1.46959958,  0.83631808],
       [ 0.69839152,  0.2665797 ,  0.90236912,  1.49918578],
       [ 0.20468323,  0.72033239,  0.44858475,  0.571171  ],
       [-0.78273335, -0.86780201,  0.10824648,  0.30602392],
       [-0.53587921,  1.40096142, -1.25310662, -1.28485856],
       [-0.65930628,  1.40096142, -1.25310662, -1.28485856],
       [-1.0295875 ,  0.

In [14]:
standardScaler.fit(X_test)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [15]:
X_test_standard = standardScaler.transform(X_test)

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
knn_clf = KNeighborsClassifier(n_neighbors = 3)

In [18]:
knn_clf.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [36]:
knn_clf.score(X_test_standard,y_test)

0.8333333333333334

In [20]:
from sklearn.preprocessing import MinMaxScaler

In [21]:
minmaxScaler = MinMaxScaler()

In [22]:
minmaxScaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [23]:
X_train_MinMaxScaler = minmaxScaler.transform(X_train)

In [24]:
X_train_MinMaxScaler

array([[0.22222222, 0.625     , 0.05357143, 0.04166667],
       [0.16666667, 0.41666667, 0.05357143, 0.04166667],
       [0.38888889, 0.33333333, 0.53571429, 0.5       ],
       [0.52777778, 0.58333333, 0.76785714, 0.91666667],
       [0.22222222, 0.20833333, 0.33928571, 0.41666667],
       [0.75      , 0.5       , 0.64285714, 0.54166667],
       [0.5       , 0.25      , 0.80357143, 0.54166667],
       [0.91666667, 0.41666667, 0.98214286, 0.83333333],
       [0.25      , 0.875     , 0.07142857, 0.        ],
       [0.52777778, 0.08333333, 0.60714286, 0.58333333],
       [0.83333333, 0.375     , 0.92857143, 0.70833333],
       [0.58333333, 0.5       , 0.75      , 0.91666667],
       [0.47222222, 0.58333333, 0.60714286, 0.625     ],
       [0.25      , 0.29166667, 0.5       , 0.54166667],
       [0.30555556, 0.70833333, 0.07142857, 0.04166667],
       [0.27777778, 0.70833333, 0.07142857, 0.04166667],
       [0.19444444, 0.625     , 0.08928571, 0.20833333],
       [0.02777778, 0.375     ,

In [25]:
minmaxScaler.fit(X_test)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [26]:
X_test_MinMaxScaler = minmaxScaler.transform(X_test)

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [29]:
knn_clf.fit(X_train_MinMaxScaler,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [30]:
knn_clf.score(X_test_MinMaxScaler,y_test)

1.0