# 如何调试梯度

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
np.random.seed(666)
X = np.random.random(size=(1000,10))

In [4]:
true_theta = np.arange(1,12,dtype=float)

In [8]:
X_b = np.hstack([np.ones((len(X),1)),X])
y = X_b.dot(true_theta) + np.random.normal(size=1000)

In [9]:
X.shape

(1000, 10)

In [10]:
y.shape

(1000,)

In [11]:
true_theta

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [13]:
def J(theta,X_b,y):
    try:
        return np.sum((y-X_b.dot(theta))**2)/len(X_b)
    except:
        return float('inf')    

In [14]:
def dJ_math(theta,X_b,y):
    return X_b.T.dot(X_b.dot(theta) - y) * 2. / len(y)

In [15]:
def dJ_debug(theta,X_b,y,epsilon=0.01):
    res = np.empty(len(theta))
    for i in range(len(theta)):
        theta_1 = theta.copy()
        theta_1[i] += epsilon
        theta_2 = theta.copy()
        theta_2[i] -= epsilon
        res[i] = (J(theta_1,X_b,y)-J(theta_2,X_b,y)) / (2*epsilon)
    return res

In [17]:
def gradient_descent(dJ,X_b,y,initial_theta,eta,n_iters=1e4,epsilon=1e-8):
    
    theta = initial_theta
    cur_iter = 0
    
    while cur_iter < n_iters:
        gradient = dJ(theta,X_b,y)
        last_theta = theta
        theta = theta - eta * gradient
        if(abs(J(theta,X_b,y)-J(last_theta,X_b,y)) < epsilon):
            break
            
        cur_iter += 1
        
    return theta    

In [18]:
X_b = np.hstack([np.ones((len(X),1)),X])
initial_theta = np.zeros(X_b.shape[1])
eta = 0.01

%time theta = gradient_descent(dJ_debug,X_b,y,initial_theta,eta)
theta

Wall time: 3.19 s


array([ 0.90835074,  2.27783675,  3.03608562,  3.96472955,  4.96383789,
        6.13271003,  7.11435903,  7.89288214,  8.89898567,  9.88136085,
       10.93881607])

In [19]:
%time theta = gradient_descent(dJ_math,X_b,y,initial_theta,eta)
theta

Wall time: 498 ms


array([ 0.90835074,  2.27783675,  3.03608562,  3.96472955,  4.96383789,
        6.13271003,  7.11435903,  7.89288214,  8.89898567,  9.88136085,
       10.93881607])