In [1]:
import numpy as np
import pandas as pd

In [2]:
summary = pd.read_excel('.\summary.xls',index_col=False)

In [3]:
nrows = len(summary)
ncols = summary.shape[1]
summary

日期   倾向     开盘     收盘     最高     最低     涨跌幅   涨跌额     成交量    成交额  \
0      2019-1-1  0.6    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
1      2019-1-2  0.6  54.19  53.33  54.33  53.09 -0.0170 -0.92   82.55  45.73   
2      2019-1-3  0.6  53.30  53.83  54.48  53.21  0.0094  0.50   69.27  38.65   
3      2019-1-4  0.6  53.43  54.74  55.15  53.38  0.0169  0.91  112.99  63.77   
4      2019-1-5  0.6    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
5      2019-1-6  0.4    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
6      2019-1-7  0.4  55.24  54.45  55.32  54.05 -0.0053 -0.29   76.59  43.26   
7      2019-1-8  0.8  54.20  53.95  54.24  53.35 -0.0092 -0.50   55.99  31.16   
8      2019-1-9  0.4  54.35  55.10  55.75  54.11  0.0213  1.15   81.91  46.74   
9     2019-1-10  0.6  55.02  55.65  55.97  54.70  0.0100  0.55   67.33  38.58   
10    2019-1-11  0.2  56.15  56.22  56.44  55.65  0.0102  0.57   45.76  26.51   
11    2019-1-12  0.2    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
12    2019-1-13  0.2    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
13    2019-1-14  0.6  55.89  55.27  56.10  55.05 -0.0169 -0.95   47.53  27.24   
14    2019-1-15  0.4  55.41  56.74  56.84  55.21  0.0266  1.47   58.63  34.14   
15    2019-1-16  0.4  56.57  56.89  57.11  56.16  0.0026  0.15   40.41  23.68   
16    2019-1-17  0.6  57.20  56.88  57.95  56.71 -0.0002 -0.01   53.51  31.68   
17    2019-1-18  0.6  57.38  58.07  58.17  56.84  0.0209  1.19   56.18  33.51   
18    2019-1-19  0.6    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
19    2019-1-20  0.6    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
20    2019-1-21  0.8  58.08  58.94  59.26  58.00  0.0150  0.87   55.98  33.95   
21    2019-1-22  0.8  58.75  58.22  58.79  57.89 -0.0122 -0.72   41.95  25.25   
22    2019-1-23  0.8  57.97  57.64  58.55  57.60 -0.0100 -0.58   37.49  22.44   
23    2019-1-24  0.6  57.76  58.58  58.67  57.37  0.0163  0.94   44.94  26.95   
24    2019-1-25  0.2  58.65  59.44  59.93  58.58  0.0147  0.86   67.25  41.30   
25    2019-1-26  0.2    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
26    2019-1-27  0.8    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
27    2019-1-28  0.8  59.95  59.67  60.56  59.35  0.0039  0.23   58.16  36.03   
28    2019-1-29  0.6  59.53  59.80  60.05  59.13  0.0022  0.13   39.52  24.28   
29    2019-1-30  0.6  59.03  59.40  60.01  58.93 -0.0067 -0.40   31.00  19.04   
..          ...  ...    ...    ...    ...    ...     ...   ...     ...    ...   
430    2020-3-6  0.8  81.57  80.91  81.92  80.80 -0.0187 -1.54   58.42  47.40   
431    2020-3-7  0.2    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
432    2020-3-8  0.6    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
433    2020-3-9  0.8  78.91  78.14  79.00  78.02 -0.0342 -2.77  105.51  82.77   
434   2020-3-10  0.6  78.14  79.18  79.78  77.83  0.0133  1.04   71.70  56.45   
435   2020-3-11  0.6  79.18  78.15  79.25  78.15 -0.0130 -1.03   59.14  46.45   
436   2020-3-12  0.8  77.25  77.65  77.48  76.53 -0.0192 -1.50   90.13  69.26   
437   2020-3-13  0.8  72.14  74.71  75.98  72.10 -0.0253 -1.94  116.62  86.16   
438   2020-3-14  0.8    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
439   2020-3-15  0.4    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
440   2020-3-16  0.0  74.50  72.00  74.52  71.80 -0.0363 -2.71   97.92  71.35   
441   2020-3-17  0.2  71.65  72.14  73.00  70.89  0.0019  0.14   95.09  68.42   
442   2020-3-18  0.6  72.53  69.87  72.88  69.85 -0.0315 -2.27   85.22  60.78   
443   2020-3-19  0.6  69.10  67.81  69.87  66.32 -0.0295 -2.06  123.68  83.86   
444   2020-3-20  0.8  68.71  69.00  69.40  67.35  0.0175  1.19   88.73  60.81   
445   2020-3-21  0.4    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
446   2020-3-22  0.8    NaN    NaN    NaN    NaN     NaN   NaN     NaN    NaN   
447   2020-3-23  0.8  66.00  66.76  67.50  6

In [4]:
df = pd.DataFrame(summary)

In [5]:
#均值填补
for i in range(1,ncols):
    nan_judgement = np.any(df.iloc[:,i].isnull())
    if (nan_judgement):
        rows = np.sum(np.array(df.iloc[:,i].isnull()==False))
        mean1 = np.sum(df.iloc[:,i]) / rows
        df.iloc[:,i] = df.iloc[:,i].fillna(value=mean1)
df

日期   倾向         开盘         收盘         最高         最低       涨跌幅  \
0      2019-1-1  0.6  79.841782  79.897624  80.667129  79.125083  0.000993   
1      2019-1-2  0.6  54.190000  53.330000  54.330000  53.090000 -0.017000   
2      2019-1-3  0.6  53.300000  53.830000  54.480000  53.210000  0.009400   
3      2019-1-4  0.6  53.430000  54.740000  55.150000  53.380000  0.016900   
4      2019-1-5  0.6  79.841782  79.897624  80.667129  79.125083  0.000993   
..          ...  ...        ...        ...        ...        ...       ...   
455   2020-3-31  0.2  70.110000  69.170000  70.350000  69.010000  0.000300   
456    2020-4-1  0.4  69.000000  69.320000  70.470000  68.900000  0.002200   
457    2020-4-2  0.2  68.400000  69.670000  69.670000  67.760000  0.005000   
458    2020-4-3  0.4  79.841782  79.897624  80.667129  79.125083  0.000993   
459    2020-4-4  0.4  79.841782  79.897624  80.667129  79.125083  0.000993   

          涨跌额         成交量        成交额      振幅       换手率  热度  
0    0.052046   65.823234  52.633036  0.0199  0.006084   1  
1   -0.920000   82.550000  45.730000  0.0229  0.007600   1  
2    0.500000   69.270000  38.650000  0.0238  0.006400   1  
3    0.910000  112.990000  63.770000  0.0329  0.010400   1  
4    0.052046   65.823234  52.633036  0.0199  0.006084   1  
..        ...         ...        ...     ...       ...  ..  
455  0.020000   42.540000  29.680000  0.0194  0.003900   1  
456  0.150000   55.690000  38.870000  0.0227  0.005100   1  
457  0.350000   51.200000  35.130000  0.0276  0.004700   1  
458  0.052046   65.823234  52.633036  0.0199  0.006084   1  
459  0.052046   65.823234  52.633036  0.0199  0.006084   1  

[460 rows x 13 columns]

In [151]:
#自定义逻辑填补
for i in range(1,ncols):
    nan_judgement = np.any(df.iloc[:,i].isnull())
    if (nan_judgement):
        for j in range(nrows):
            if(np.isnan(df.iloc[j,i])):
                if j==0:
                    df.iloc[j,i] = df.iloc[j+1,i] - (df.iloc[j+2,i]-df.iloc[j+1,i])
                elif (df.iloc[j-1,i]!=0 and df.iloc[j-2,i]!=0):
                    df.iloc[j,i] = df.iloc[j-1,i] + (df.iloc[j-1,i] - df.iloc[j-2,i])
df

日期   倾向     开盘     收盘     最高     最低     涨跌幅   涨跌额     成交量    成交额  \
0      2019-1-1  0.6  55.08  52.83  54.18  52.97 -0.0434 -2.34   95.83  52.81   
1      2019-1-2  0.6  54.19  53.33  54.33  53.09 -0.0170 -0.92   82.55  45.73   
2      2019-1-3  0.6  53.30  53.83  54.48  53.21  0.0094  0.50   69.27  38.65   
3      2019-1-4  0.6  53.43  54.74  55.15  53.38  0.0169  0.91  112.99  63.77   
4      2019-1-5  0.6  53.56  55.65  55.82  53.55  0.0244  1.32  156.71  88.89   
..          ...  ...    ...    ...    ...    ...     ...   ...     ...    ...   
455   2020-3-31  0.2  70.11  69.17  70.35  69.01  0.0003  0.02   42.54  29.68   
456    2020-4-1  0.4  69.00  69.32  70.47  68.90  0.0022  0.15   55.69  38.87   
457    2020-4-2  0.2  68.40  69.67  69.67  67.76  0.0050  0.35   51.20  35.13   
458    2020-4-3  0.4  67.80  70.02  68.87  66.62  0.0078  0.55   46.71  31.39   
459    2020-4-4  0.4  67.20  70.37  68.07  65.48  0.0106  0.75   42.22  27.65   

         振幅     换手率  热度  
0    0.0220  0.0088   1  
1    0.0229  0.0076   1  
2    0.0238  0.0064   1  
3    0.0329  0.0104   1  
4    0.0420  0.0144   1  
..      ...     ...  ..  
455  0.0194  0.0039   1  
456  0.0227  0.0051   1  
457  0.0276  0.0047   1  
458  0.0325  0.0043   1  
459  0.0374  0.0039   1  

[460 rows x 13 columns]

In [6]:
from sklearn.feature_selection import VarianceThreshold

In [7]:
column_names = df.columns.values
time_stamp = df.iloc[:,0]
time_stamp = pd.DataFrame(time_stamp)
time_stamp

日期
0      2019-1-1
1      2019-1-2
2      2019-1-3
3      2019-1-4
4      2019-1-5
..          ...
455   2020-3-31
456    2020-4-1
457    2020-4-2
458    2020-4-3
459    2020-4-4

[460 rows x 1 columns]

In [8]:
#to_numpy
data = np.array(df.iloc[:,1:])

In [9]:
#kill_low_variance
threshold = VarianceThreshold(threshold=0.0)
res = threshold.fit_transform(data)

In [10]:
for i in range(len(res)):
    if(res[i][0]>0.5):
        res[i][0] = 1
    else:
        res[i][0] = 0
res[:,0]

array([1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1.,
       0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 0., 0.

In [11]:
res.shape

(460, 11)

In [12]:
#mean_01 or selfrule_01
for i in [5,6]:
    for j in range(len(res)):
        if(res[j][i]>=0):
            res[j][i] = 1
        else:
            res[j][i] = 0
res[:,[5,6]]

array([[1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.

In [13]:
#mean or selfrule
temp_res = res.copy()
for i in [1,2,3,4,7,8,9,10]:
    for j in range(1,len(res)):
        if((temp_res[j][i]-temp_res[j-1][i])>=0):
            res[j][i] = 1
        else:
            res[j][i] = 0
for i in range(1,11):
    res[0][i] = 0

In [14]:
#subtract with mean or selfrule
temp_res = res.copy()
for i in [1,2,3,4,7,8,9,10]:
    for j in range(1,len(res)):
        res[j][i] = temp_res[j][i]-temp_res[j-1][i]
for i in range(1,11):
    res[0][i] = 0

In [15]:
res

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  1.,  1.],
       [ 1.,  0.,  1., ...,  0.,  0., -1.],
       ...,
       [ 0.,  0.,  0., ..., -1.,  0., -1.],
       [ 0.,  1.,  0., ...,  1., -1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.]])

In [159]:
res_to_pandas = pd.DataFrame(res,columns=column_names[1:-1])
res_total = pd.merge(time_stamp,res_to_pandas,on=time_stamp.index)
res_total = res_total.iloc[:,1:]

In [160]:
res_total.to_excel('./vt_rulefillna_sub_summary.xls')

In [16]:
#MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
minMaxScaler = MinMaxScaler()
minMaxScaler.fit(res)
print(minMaxScaler.scale_)
minMax_res = minMaxScaler.transform(res)
print(minMax_res[:5,:])

[1.  0.5 0.5 0.5 0.5 1.  1.  0.5 0.5 0.5 0.5]
[[1.  0.5 0.5 0.5 0.5 0.  0.  0.5 0.5 0.5 0.5]
 [1.  0.5 0.5 0.5 0.5 0.  0.  1.  0.5 1.  1. ]
 [1.  0.5 1.  1.  1.  1.  1.  0.  0.5 0.5 0. ]
 [1.  1.  0.5 0.5 0.5 1.  1.  1.  1.  0.5 1. ]
 [1.  0.5 0.5 0.5 0.5 1.  1.  0.  0.  0.  0. ]]


In [17]:
#StandardScaler
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
standardScaler.fit(res)
print(standardScaler.scale_)
standard_res = standardScaler.transform(res)
print(standard_res[:5,:])

[0.49348784 0.69313062 0.69313062 0.68046951 0.68998712 0.46796729
 0.46796729 0.72681232 0.73276995 0.77318908 0.72381511]
[[ 0.85020376 -0.00313637 -0.00313637 -0.00319473 -0.00315066 -1.44473123
  -1.44473123 -0.00299102 -0.00296671 -0.00281162 -0.00300341]
 [ 0.85020376 -0.00313637 -0.00313637 -0.00319473 -0.00315066 -1.44473123
  -1.44473123  1.37287999 -0.00296671  1.29053307  1.37856487]
 [ 0.85020376 -0.00313637  1.43959314  1.46637884  1.44615175  0.69217027
   0.69217027 -1.37886204 -0.00296671 -0.00281162 -1.38457169]
 [ 0.85020376  1.43959314 -0.00313637 -0.00319473 -0.00315066  0.69217027
   0.69217027  1.37287999  1.36171808 -0.00281162  1.37856487]
 [ 0.85020376 -0.00313637 -0.00313637 -0.00319473 -0.00315066  0.69217027
   0.69217027 -1.37886204 -1.36765149 -1.29615631 -1.38457169]]


In [18]:
#to pandas and merge
res_temp = standard_res
res_to_pandas = pd.DataFrame(res_temp,columns=column_names[1:-1])
print(res_to_pandas)
res_total = pd.merge(time_stamp,res_to_pandas,on=time_stamp.index)
res_total = res_total.iloc[:,1:]

           倾向        开盘        收盘        最高        最低       涨跌幅       涨跌额  \
0    0.850204 -0.003136 -0.003136 -0.003195 -0.003151 -1.444731 -1.444731   
1    0.850204 -0.003136 -0.003136 -0.003195 -0.003151 -1.444731 -1.444731   
2    0.850204 -0.003136  1.439593  1.466379  1.446152  0.692170  0.692170   
3    0.850204  1.439593 -0.003136 -0.003195 -0.003151  0.692170  0.692170   
4    0.850204 -0.003136 -0.003136 -0.003195 -0.003151  0.692170  0.692170   
..        ...       ...       ...       ...       ...       ...       ...   
455 -1.176189  1.439593  1.439593  1.466379  1.446152  0.692170  0.692170   
456 -1.176189 -1.445866 -0.003136 -0.003195 -1.452453  0.692170  0.692170   
457 -1.176189 -0.003136 -0.003136 -1.472768 -0.003151  0.692170  0.692170   
458 -1.176189  1.439593 -0.003136  1.466379  1.446152  0.692170  0.692170   
459 -1.176189 -0.003136 -0.003136 -0.003195 -0.003151  0.692170  0.692170   

          成交量       成交额        振幅       换手率  
0   -0.002991 -0.002967 -0.00

In [442]:
res_total

日期        倾向        开盘            收盘        最高            最低  \
0      2019-1-1  0.243180  0.000000 -1.834094e-15  0.000000 -1.805904e-15   
1      2019-1-2  0.243180 -3.275086 -3.428895e+00 -3.380409 -3.308517e+00   
2      2019-1-3  0.243180 -3.388716 -3.364364e+00 -3.361156 -3.293267e+00   
3      2019-1-4  0.243180 -3.372118 -3.246916e+00 -3.275161 -3.271664e+00   
4      2019-1-5  0.243180  0.000000 -1.834094e-15  0.000000 -1.805904e-15   
..          ...       ...       ...           ...       ...           ...   
455   2020-3-31 -1.477785 -1.242503 -1.384538e+00 -1.324219 -1.285416e+00   
456    2020-4-1 -0.617302 -1.384222 -1.365179e+00 -1.308816 -1.299395e+00   
457    2020-4-2 -1.477785 -1.460827 -1.320007e+00 -1.411498 -1.444265e+00   
458    2020-4-3 -0.617302  0.000000 -1.834094e-15  0.000000 -1.805904e-15   
459    2020-4-4 -0.617302  0.000000 -1.834094e-15  0.000000 -1.805904e-15   

              涨跌幅           涨跌额       成交量           成交额            振幅  \
0   -1.525390e-17  6.317364e-18  0.000000  3.992657e-16  4.279545e-16   
1   -1.265767e+00 -8.849782e-01  0.728030 -3.878930e-01  3.700078e-01   
2    5.913724e-01  4.078297e-01  0.150020 -7.857299e-01  4.810223e-01   
3    1.118969e+00  7.811053e-01  2.052926  6.258044e-01  1.603503e+00   
4   -1.525390e-17  6.317364e-18  0.000000  3.992657e-16  4.279545e-16   
..            ...           ...       ...           ...           ...   
455 -4.877800e-02 -2.917577e-02 -1.013399 -1.289769e+00 -6.171545e-02   
456  8.487976e-02  8.917989e-02 -0.441047 -7.733678e-01  3.453379e-01   
457  2.818491e-01  2.712655e-01 -0.636474 -9.835245e-01  9.497504e-01   
458 -1.525390e-17  6.317364e-18  0.000000  3.992657e-16  4.279545e-16   
459 -1.525390e-17  6.317364e-18  0.000000  3.992657e-16  4.279545e-16   

          换手率  
0    0.000000  
1    0.714752  
2    0.149049  
3    2.034726  
4    0.000000  
..        ...  
455 -1.029499  
456 -0.463796  
457 -0.652363  
458  0.000000  
459  0.000000  

[460 rows x 12 columns]

In [443]:
# res_total.to_excel('./vt_mm_meanfillna_summary.xls')
# res_total.to_excel('./vt_mm_rulefillna_summary.xls')
# res_total.to_excel('./vt_st_rulefillna_summary.xls')
res_total.to_excel('./vt_st_meanfillna_summary.xls')